name: test-clang-format

# TODO: Remove main branch at some point
on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Want to ignore cfortran.h, lapack_qz.h, superlu.c, superlu_dist.c
    - uses: PuneetMatharu/clang-format-lint-action@v0.13
      with:
        files: ^(src)\/(?!.*(cfortran|lapack_qz))(.+)\.(h|hpp|cc|cpp|tpp)$
        clangFormatVersion: 12
        style: file
        inplace: True

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_user_name: clang-format-bot
        commit_message: 'Automated commit of clang-format CI changes.'
