name: test-clang-format

# TODO: Remove main branch at some point
on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # Ignore cfortran.h, lapack_qz.h, superlu.c, superlu_dist.c
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: 'src'
        exclude: 'src/generic/cfortran.h src/generic/lapack_qz.h src/generic/superlu.c src/generic/superlu_dist.c'
        extensions: 'h,cc,tpp'
        clangFormatVersion: 12
        style: file
        inplace: True

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_user_name: clang-format-bot
        commit_message: 'Automated commit of clang-format CI changes.'
